### ISSUE TITLE
Question: Can you please provide an example with if-statements? Does it work with pytest hypothesis?

### ISSUE THREAD

**Issue by bcm0** [aragilar/pytest-mpi#15]
Like suggested in the [docs](https://pytest-mpi.readthedocs.io/en/latest/usage.html) I run `mpirun -n 2 python -m pytest --with-mpi`.
```python
import pytest
from mpi4py import MPI
import hypothesis.strategies as st

@pytest.mark.mpi
@given(senddata=st.integers())
def test_simple(self, senddata):
    comm = MPI.COMM_WORLD
    rank = comm.Get_rank()

    if rank == 0:
        comm.send(senddata, dest=1)
    elif rank == 1:
        recvdata = comm.recv(source=0)
        assert senddata == recvdata
```
The input arguments get mixed and the assert fails. 
Most likely this is due to the tests being run twice with `mpirun -n 2`.
I would love to see a working example.

**Comment by aragilar** [comment]
h5py uses pytest-mpi (that's why I wrote it).

I suspect in your case though the problem is hypothesis starts with different random numbers or uses a different seed - you probably need to configure it (or the environment it runs in) to make sure both processes use the same ordering of numbers.

**Comment by bcm0** [comment]
I found [hypothesis seeds](https://hypothesis.readthedocs.io/en/latest/reproducing.html#reproducing-a-test-run-with-seed) and now my problem is fixed. 
Thank you very much!
`mpirun -n 2 python -m pytest --with-mpi --hypothesis-seed 1234`

**Comment by adnion** [comment]
Pytest-mpi does not work with hypothesis in a reliable manner.
Running it with `mpirun` seems to be a very bad idea although it often works quite well for few test cases with small arrays.
I get arbitrary python segmentation faults, bus errors or aborts. These faults are probably related to hypothesis because I use it in a different way.
I don't know which path to choose. 

Any alternative to the hypothesis framework? Is there a way to avoid mpirun? Unfortunately I need 2 processes to test blocking communication.
